version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/kaz-under-the-bridge/google-cloud-ops-mcp

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  gocritic:
    disabled-checks:
      - exitAfterDefer
      - ifElseChain

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic

  max-issues-per-linter: 50
  max-same-issues: 10
